-- LƯU Ý CHẠY SCRIPT QUERY 
USE SQLDBHowKTeam
GO

-- CẤU TRÚC TRUY VẤN
SELECT * FROM dbo.BOMON -- LẤY HẾT DỮ LIỆU BẢNG BỘ MÔN.

SELECT * FROM dbo.GIAOVIEN -- LẤY HẾT DỮ LIỆU BẢNG GIÁO VIÊN
SELECT * FROM dbo.THAMGIADT -- LẤY HẾT DỮ LIỆU BẢNG NGƯỜI THÂN
SELECT * FROM dbo.DETAI -- LẤY HẾT DỮ LIỆU BẢNG NGƯỜI THÂN

-- ĐỔI TÊN CÔT HIỂN THỊ
SELECT MAGV AS N'MÃ GIÁO VIÊN', HOTEN AS N'HỌ VÀ TÊN' FROM  dbo.GIAOVIEN

SELECT * FROM dbo.GIAOVIEN, dbo.BOMON

SELECT MAGV, HOTEN FROM dbo.GIAOVIEN -- LẤY DỮ LIỆU MAGV VÀ HOTEN TRONG BẢNG GIÁO VIÊN

-- XUẤT RA MÃ GIÁO VIÊN + TÊN + TÊN BỘ MÔN GIÁO VIÊN ĐÓ DẠY
SELECT MAGV, HOTEN, TENBM FROM dbo.GIAOVIEN, dbo.BOMON

SELECT GV.MAGV, GV.HOTEN, BM.TENBM FROM dbo.GIAOVIEN AS GV, dbo.BOMON AS BM

-- BÀI TẬP
-- 1. TRUY XUẤT THÔNG TIN BẢNG THAM GIA ĐỀ TÀI.
SELECT * FROM dbo.THAMGIADT
-- 2. LẤY RA MÃ KHOA VÀ TÊN KHOA TƯƠNG ỨNG.
SELECT K.MAKHOA, K.TENKHOA FROM dbo.KHOA AS K
-- 3. LẤY RA HỌ MÃ GIÁO VIÊN, TÊN GV VÀ HỌ TÊN NGƯỜI THÂN TƯƠNG ỨNG.
SELECT GV.MAGV, GV.HOTEN, NT.TEN FROM dbo.GIAOVIEN AS GV, dbo.NGUOITHAN AS NT

-- 4. LẤY RA MÃ GV, TÊN GV VÀ TÊN KHOA CỦA GIÁO VIÊN ĐÓ LÀM VIỆC. GỢI Ý: BỘ MÔN NẰM TRONG KHOA.
SELECT GV.MAGV, GV.HOTEN, K.TENKHOA FROM dbo.GIAOVIEN AS GV, dbo.BOMON AS BM, dbo.KHOA AS K
WHERE (GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA)

-- 5. LẤY HẾT TẤT CẢ GV KHI MÀ LƯƠNG HỌ LỚN HƠN 2000.
SELECT * FROM dbo.GIAOVIEN AS GV WHERE GV.LUONG > 2000.

-- 6. LẤY HẾT TẤT CẢ GV KHI MÀ LƯƠNG HỌ LỚN HƠN 2000 VÀ NỮ
SELECT * FROM dbo.GIAOVIEN AS GV WHERE GV.LUONG > 2000 AND GV.PHAI = N'Nữ'

-- 7. LẤY HẾT TẤT CẢ GV LỚN HƠN 50 TUỔI
SELECT * FROM dbo.GIAOVIEN AS GV WHERE (YEAR(GETDATE()) - YEAR(GV.NGSINH)) > 50

-- 8. LẤY RA TÊN GV, NĂM SINH VÀ TUỔI GV NHỎ HƠN 50 TUỔI
SELECT GV.HOTEN, GV.NGSINH FROM dbo.GIAOVIEN AS GV WHERE (YEAR(GETDATE()) - YEAR(GV.NGSINH)) <= 50

-- 9. LẤY DATA GV CÓ THU NHẬP TỪ 2000 ĐẾN 2200
SELECT GV.HOTEN, GV.NGSINH FROM dbo.GIAOVIEN AS GV WHERE GV.LUONG BETWEEN 2000 AND 2200 -- C1
SELECT GV.HOTEN, GV.NGSINH FROM dbo.GIAOVIEN AS GV WHERE GV.LUONG >=2000 AND GV.LUONG <= 2200 -- C2

-- 10. LẤY RA GIÁO VIÊN LÀ TRƯỞNG BỘ MÔN
SELECT GV.* FROM dbo.GIAOVIEN AS GV, dbo.BOMON AS BM WHERE GV.MAGV = BM.TRUONGBOMON

-- 11. ĐẾM SỐ LƯỢNG NGƯỜI THÂN GIÁO VIÊN CÓ MÃ LÀ 007.
-- COUNT(*) -> ĐẾM SỐ LƯỢNG TẤT CẢ RECORD.
-- COUNT(TÊN TRƯỜNG) -> ĐẾM SỐ LƯỢNG CỦA TÊN TRƯỜNG ĐÓ
SELECT COUNT(*) AS N'SÔ LƯỢNG GIÁO VIÊN' FROM dbo.GIAOVIEN AS GV, dbo.NGUOITHAN AS NT
WHERE GV.MAGV = N'007' AND GV.MAGV = NT.MAGV

-- 12. LẤY RA TÊN GIÁO VIÊN VÀ TÊN ĐỀ TÀI NGƯỜI ĐÓ THAM GIA KHI MÀ NGƯỜI ĐÓ THAM GIA NHIỀU HƠN 1 LẦN. (truy vấn lồng)
SELECT GV.HOTEN, DT.TENDT FROM dbo.GIAOVIEN AS GV, dbo.DETAI AS DT, dbo.THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT

-- BÀI TẬP
-- 1. XUẤT RA MÀN HÌNH GIÁO VIÊN VÀ GIÁO VIÊN CHỦ NHIỆM NGƯỜI ĐÓ.
SELECT GV1.HOTEN AS N'GIAÓ VIÊN', GV2.HOTEN AS N'GIÁO VIÊN CHỦ NHIỆM' FROM dbo.GIAOVIEN AS GV1, dbo.GIAOVIEN AS GV2
WHERE GV1.MAGV = GV2.GVQLCM

-- 2. XUẤT RA LƯỢNG GIÁO VIÊN KHOA CNTT.
SELECT COUNT(*) AS N'SỐ LƯỢNG GIÁO VIÊN KHOA CNTT' FROM dbo.GIAOVIEN AS GV, dbo.BOMON AS BM, dbo.KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.MAKHOA = 'CNTT' AND BM.MAKHOA = 'CNTT'

-- 3. XUẤT RA THÔNG TIN GIÁO VIÊN VÀ ĐỀ TÀI NGƯỜI ĐÓ THAM GIA KHI MÀ ĐỀ TÀI ĐẠT.
SELECT GV.HOTEN, DT.TENDT FROM dbo.GIAOVIEN AS GV, dbo.DETAI AS DT, dbo.THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.KETQUA = N'Đạt' AND TGDT.MADT = DT.MADT
