USE NORTHWND
GO

/*
NHỎ NHẤT -> SELECT MIN(...)
LỚN NHẤT -> SELECT MAX(...)
SELECT MIN/MAX(...)
FROM TABLE_NAME

TÌM RA GIÁ TRỊ LỚN NHẤT/NHỎ NHẤT CỦA CỘT
*/

-- VIẾT CÂU LỆNH SQL TÌM GIÁ TRỊ MIN CỦA BẢNG PRODUCT
SELECT MIN(P.UnitPrice) AS [GIA THAP NHAT]
FROM dbo.Products AS P

-- LẤY RA NGÀY ĐẶT HÀNG GẦN NHẤT TỪ BẢNG ODERS.
SELECT MAX(O.OrderDate) AS [NGAY NGAN NHAT] FROM dbo.Orders AS O
