USE HowKteam
GO

-- KIỂU DỮ LIỆU TỰ ĐỊNH NGHĨA.
-- EXEC SP_ADDTYPE 'TÊN KIỂU DỮ LIỆU', 'KIỂU DỮ LIỆU THỰC TẾ', 'NOT NULL' (CÓ HAY KO ĐỀU ĐƯỢC).

EXEC SP_ADDTYPE 'NNAME', 'NVARCHAR(100)', 'NOT NULL'

CREATE TABLE TESTTYPE
(
	NAME NNAME,
	ADDRESS NVARCHAR(500)
)
GO

EXEC SP_ADDTYPE 'NADDRESS', 'NVARCHAR(500)', 'NOT NULL'

-- XÓA TYPE
EXEC sp_droptype 'NADDRESS'
