USE HowKteam
GO

-- INSERT 10000 RECORD VÀO BẢNG BOMON
-- KO TRÙNG ID
-- TÊN BỘ MÔN TĂNG DẦN
DECLARE @i INT = 100
WHILE (@i < 10000) -- ĐIỀU KIỆN DỪNG
BEGIN
	INSERT INTO [dbo].[BOMON] (MABM, TENBM, PHONG, DIENTHOAI, TRUONGBM, MAKHOA, NGAYNHANCHUC)
	VALUES (
			@i,
			@i,
			'B15',
			'0000000000',
			NULL,
			'CNTT',
			GETDATE()
			)
	SET @i += 1
END

SELECT * FROM [dbo].[BOMON]