CREATE DATABASE NVDB
ON
(
	NAME = 'NVDB_DATA',
	FILENAME = 'D:\02_DATA\06_SQL\TUHOCSQL\28_TAO_DATABASE\NVDB_DATA.mdf',
	SIZE = 10MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB)
LOG ON
(
	NAME = 'NVDB_LOG',
	FILENAME = 'D:\02_DATA\06_SQL\TUHOCSQL\28_TAO_DATABASE\NVDB_LOG.ldf',
	SIZE = 5MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 5MB
)
