USE NORTHWND
GO
/*
SELECT COLUMN1, COLUMN2,...
FROM TABLE_NAME
ORDER BY COLUMN1, COLUMN2,... ASC|DESC

ASC: SẮP XẾP TĂNG DẦN
DESC: SẮP XẾP GIẢM DẦN
*/

-- LIỆT KÊ TẤT CẢ CÁC NHÀ CUNG CẤP THEO THỨ TỰ TÊN ĐƠN VỊ COMPANYNAME TỪ A -> Z
SELECT SU.CompanyName FROM dbo.Suppliers AS SU
ORDER BY SU.CompanyName ASC

