USE NORTHWND
GO

-- TẠO 1 BẢNG TẠM CUSTOMER_1 TỪ CUSTOMER
SELECT *
INTO CUSTOMER_TEMP
FROM [dbo].[Customers]

-- XÓA ĐI KHÁCH HÀNG 'ALFKI'
DELETE FROM [dbo].[CUSTOMER_TEMP]
WHERE [CustomerID] LIKE 'ALFKI'

-- XÓA ĐI KHÁCH HÀNG CÓ QUỐC GIA LÀ USA
DELETE FROM [dbo].[CUSTOMER_TEMP]
WHERE [Country] LIKE 'USA'

-- XÓA SẠCH 1 BẢNG
DELETE FROM [dbo].[CUSTOMER_TEMP];

-- TỪ CSDL NORTHWIND SỬ DỤNG SELECT INTO ĐỂ TẠO RA BẢNG TẠM THỜI TRƯỚC KHI DUNG CÂU LỆNH DELETE.
-- 1. VIẾT CÂU LỆNH DELETE ĐỂ XÓA 1 ĐƠN HÀNG CỤ THỂ. VÍ DỤ: XÓA ĐƠN ĐẶT HÀNG CÓ ORDER ID LÀ 10248.\
SELECT *
INTO ORDER_TEMP
FROM [dbo].[Orders];

DELETE FROM [dbo].[ORDER_TEMP]
WHERE [OrderID] = 10248;
-- 2. XÓA TẤT CẢ SẢN PHẨM TỪ BẢNG PRODUCT CÓ SỐ LƯỢNG TỒN KHO (UnitslnStock) bằng 0.
SELECT *
INTO PRODUCTS_TEMP
FROM [dbo].[Products]

DELETE FROM [dbo].[PRODUCTS_TEMP]
WHERE [UnitsInStock] = 0;

DROP TABLE [dbo].[ORDER_TEMP];
DROP TABLE [dbo].[PRODUCTS_TEMP];
DROP TABLE [dbo].[HIGHVALUEORDER];
DROP TABLE [dbo].[HIGHVALUEORDER_CTE];
DROP TABLE [dbo].[HighValuepRODUCTS];
DROP TABLE [dbo].[ORDER_TO_USA];
DROP TABLE [dbo].[sinh_vien];
-- 3. XÓA TẤT CẢ ĐƠN HÀNG VÀ CHI TIẾT ĐẶT HÀNG LIÊN QUAN ĐẾN MỘT KHÁCH HÀNG CỤ THỂ DỰA THEO CUSTOMERID.
SELECT *
INTO ORDER_TEMP
FROM [dbo].[Orders];

SELECT *
INTO Order_Details_TEMP
FROM [dbo].[Order Details];

DELETE [dbo].[Order_Details_TEMP] FROM [dbo].[ORDER_TEMP] AS OT
JOIN [dbo].[Order_Details_TEMP] AS ODT ON ODT.OrderID = OT.OrderID
WHERE OT.[CustomerID] LIKE 'VINET';

DELETE FROM [dbo].[ORDER_TEMP]
WHERE  [CustomerID] LIKE 'VINET';

DROP TABLE [dbo].[Order_Details_TEMP];
DROP TABLE [dbo].[ORDER_TEMP];
