USE NORTHWND
GO

-- TẠO RA BẢNG MỚI VỚI CÁC SẢN PHẨM > 50.
SELECT *
INTO HighValuepRODUCTS 
FROM [dbo].[Products] AS PR
WHERE PR.UnitPrice > 50;

-- TẠO RA BẢNG MỚI VỚI ĐƠN HÀNG GIAO ĐẾN MỸ (USA)
SELECT *
INTO ORDER_TO_USA
FROM [dbo].[Orders] AS O
WHERE O.ShipCountry LIKE 'USA'

-- TẠO 1 BẢNG 'CUSTOMERLONDON' TỪ BẢNG CUSTOMER TRONG CƠ SỞ DỮ LIỆU ĐỂ CHỨA INFOR CÁC KHÁCH HÀNG ĐẾN TỪ LONDON.
SELECT *
INTO CUSTOMERLONDON
FROM [dbo].[Customers] AS CU
WHERE CU.Country LIKE 'London'

-- TẠO 1 BẢNG 'HIGHVALUEORDER' ĐỂ CHỨA THÔNG TIN VỀ CÁC ĐƠN HÀNG CÓ TỔNG GIÁ TRỊ ĐẶT HÀNG LỚN HƠN 1000 ĐÔ LA.
DROP TABLE [dbo].[HIGHVALUEORDER]
DROP TABLE [dbo].[HIGHVALUEORDER_CTE]

WITH TOTAL_PRICE_CTE AS (
	SELECT [OrderID], SUM(OD.Quantity * OD.UnitPrice) AS [TOTAL_PRICE]
	FROM [dbo].[Order Details] AS OD
	GROUP BY [OrderID]
)
SELECT O.*, TPC.TOTAL_PRICE AS [PRICE_ORDER]
INTO HIGHVALUEORDER_CTE
FROM [dbo].[Orders] AS O
JOIN TOTAL_PRICE_CTE AS TPC ON TPC.OrderID = O.OrderID
WHERE TPC.TOTAL_PRICE > 1000

SELECT O.OrderID,  SUM(OD.Quantity * OD.UnitPrice) AS [TOTAL_PRICE]
INTO HIGHVALUEORDER
FROM [dbo].[Orders] AS O
JOIN [dbo].[Order Details] AS OD ON OD.OrderID = O.OrderID
WHERE O.OrderID = OD.OrderID
GROUP BY O.OrderID
HAVING SUM(OD.Quantity * OD.UnitPrice) > 1000
