USE HowKteam
GO

DROP TABLE IF EXISTS TESTCHECK
CREATE TABLE TESTCHECK
(
		ID INT PRIMARY KEY IDENTITY,
		LUONG INT
)
GO

ALTER TABLE [dbo].[TESTCHECK] ADD CONSTRAINT CK_LUONG
CHECK (LUONG > 3000 AND LUONG < 9000)

INSERT [dbo].[TESTCHECK] ([LUONG])
VALUES (10001);
