USE HowKteam
GO

-- LƯƠNG TRUNG BÌNH GIÁO VIÊN
DECLARE @LUONG_TRUNG_BINH INT
DECLARE @TOTAL_GIAO_VIEN INT

SELECT @TOTAL_GIAO_VIEN = COUNT(*) FROM [dbo].[GIAOVIEN]
SELECT @LUONG_TRUNG_BINH = SUM([LUONG]) / @TOTAL_GIAO_VIEN FROM [dbo].[GIAOVIEN]

PRINT @LUONG_TRUNG_BINH

DECLARE @MA_GV CHAR(5) = '006'
DECLARE @LUONG_MA_GV INT = 0
SELECT @LUONG_MA_GV = [LUONG] FROM [dbo].[GIAOVIEN] WHERE @MA_GV = [MAGV]
-- NẾU LƯƠNG GIÁO VIÊN @MA_GV > @LUONG_TRUNG_BINH
-- XUẤT RA LỚN HƠN
-- NGƯỢC LẠI NHỎ HƠN

IF @LUONG_MA_GV > @LUONG_TRUNG_BINH
	PRINT N'LỚN HƠN'
ELSE
	PRINT N'NHỎ HƠN'

-- NẾU MUỐN CHẠY NHIỀU CÂU LỆNH TRONG IF THÌ DÙNG BEGIN VÀ END

-- VÍ DỤ 2: DỰA VÀO LƯƠNG. NẾU LƯƠNG > LƯƠNG TRUNG BÌNH HIỆN TẠI THÌ SẼ CẬP NHẬT DỮ LIỆU LƯƠNG CHO TẤT CẢ GIÁO VIÊN BẰNG CON SỐ ĐÓ.
-- NGƯỢC LẠI THÌ SẼ CẬP NHẬT MỖI GIÁO VIÊN NỮ.
DECLARE @LUONG_TRUNG_BINH2 INT
DECLARE @TOTAL_GIAO_VIEN2 INT

SELECT @TOTAL_GIAO_VIEN2 = COUNT(*) FROM [dbo].[GIAOVIEN]
SELECT @LUONG_TRUNG_BINH2 = SUM([LUONG]) / @TOTAL_GIAO_VIEN2 FROM [dbo].[GIAOVIEN]

DECLARE @LUONG INT = 1500
IF (@LUONG > @LUONG_TRUNG_BINH2)
	BEGIN
		UPDATE [dbo].[GIAOVIEN]
		SET [LUONG] = @LUONG
	END
ELSE
BEGIN
		UPDATE [dbo].[GIAOVIEN]
		SET [LUONG] = @LUONG
		WHERE [PHAI] = N'Nữ'
END
