USE HowKteam
GO

-- XUẤT RA SỐ LƯỢNG GIÁO VIÊN TRONG TỪNG BỘ MÔN MÀ SỐ GIÁO VIÊN LỚN HƠN 2.
SELECT BM.MABM, COUNT(*) AS [totalTeacher]
FROM [dbo].[BOMON] AS BM
JOIN [dbo].[GIAOVIEN] AS GV ON GV.MABM = BM.MABM
GROUP BY BM.MABM
HAVING COUNT(*) > 2

-- XUẤT RA MỨC LƯƠNG VÀ TỔNG TUỔI CỦA GIÁO VIÊN NHẬN MỨC LƯƠNG ĐÓ.
-- VÀ CÓ NGƯỜI THÂN.
-- VÀ CÓ TUỔI LỚN HƠN TUỔI TRUNG BÌNH.
SELECT GV.LUONG, SUM(YEAR(GETDATE()) - YEAR(GV.NGSINH)) AS [TONGTUOI]
FROM [dbo].[GIAOVIEN] AS GV
JOIN [dbo].[NGUOITHAN] AS NT ON NT.MAGV = GV.MAGV
GROUP BY GV.LUONG, GV.NGSINH
HAVING YEAR(GETDATE()) - YEAR(GV.NGSINH) > 
	   (
			(SELECT SUM(YEAR(GETDATE()) - YEAR(NGSINH)) FROM [dbo].[GIAOVIEN]) / 
			(SELECT COUNT(*) FROM [dbo].[GIAOVIEN])
	   );

-- 
SELECT GV.LUONG, SUM(YEAR(GETDATE()) - YEAR(GV.NGSINH)) AS [TONGTUOI]
FROM [dbo].[GIAOVIEN] AS GV, [dbo].[NGUOITHAN] AS NT
WHERE GV.MAGV = NT.MAGV AND GV.MAGV IN (SELECT [MAGV] FROM [dbo].[NGUOITHAN])
GROUP BY GV.LUONG, GV.NGSINH
HAVING YEAR(GETDATE()) - YEAR(GV.NGSINH) > 
	   (
			(SELECT SUM(YEAR(GETDATE()) - YEAR(NGSINH)) FROM [dbo].[GIAOVIEN]) / 
			(SELECT COUNT(*) FROM [dbo].[GIAOVIEN])
	   );